name: Flake8

on:
  push:
    branches: [ main ]
    paths:
      - 'src/black_star/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/black_star/*'
  workflow_dispatch:

jobs:
  pytest:
    name: flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Run flake8
        run: |
          python -m flake8 --max-line-length=119