name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/black_star/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/black_star/*'
  workflow_dispatch:

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip poetry
          python3 -m pip poetry install -vvv
      - name: Run pytest
        run: |
          poetry run pytest -ra -v